; Tambo Sound Driver by TakuikaNinja

; NTSC period table generated by mktables.py
; (includes a C8 note entry currently only accessible via PAL transposition)
periodTableLo:
	.byte $f1,$7f,$13,$ad,$4d,$f3,$9d,$4c,$00,$b8,$74,$34
	.byte $f8,$bf,$89,$56,$26,$f9,$ce,$a6,$80,$5c,$3a,$1a
	.byte $fb,$df,$c4,$ab,$93,$7c,$67,$52,$3f,$2d,$1c,$0c
	.byte $fd,$ef,$e1,$d5,$c9,$bd,$b3,$a9,$9f,$96,$8e,$86
	.byte $7e,$77,$70,$6a,$64,$5e,$59,$54,$4f,$4b,$46,$42
	.byte $3f,$3b,$38,$34,$31,$2f,$2c,$29,$27,$25,$23,$21
	.byte $1f,$1d,$1b,$1a,$18,$17,$15,$14,$13,$12,$11,$10
	.byte $0f,$0e,$0d
periodTableHi:
	.byte $07,$07,$07,$06,$06,$05,$05,$05,$05,$04,$04,$04
	.byte $03,$03,$03,$03,$03,$02,$02,$02,$02,$02,$02,$02
	.byte $01,$01,$01,$01,$01,$01,$01,$01,$01,$01,$01,$01
;	.byte $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
;	.byte $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
;	.byte $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
;	.byte $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
;	.byte $00,$00,$00

; indexed by soundRegion (0-2):
; NTSC = use note lookup as-is, tempo 150
; PAL = transpose up 1 semitone (dirty hack), tempo 125
; DenDy = use note lookup as-is, tempo 125
tambo_noteAdjustments:
	.byte 0, 1, 0
tambo_tickRates:
	.byte 150, 125, 125

; APU init code based on https://www.nesdev.org/wiki/APU_basics#Register_initialization
tambo_registerInitTable:
	.byte $30,$08,$00,$00
	.byte $30,$08,$00,$00
	.byte $80,$00,$00,$00
	.byte $30,$00,$00,$00
	.byte $00,$00,$00,$00
; dirty hack: point note data to one of these 0s when starting a track, 
; so readNote detects it as a pattern terminator
ALWAYS_ZERO = tambo_registerInitTable+16
.assert ALWAYS_ZERO >= $8000, error, "Sound driver must be located >= $8000"

; toggle pause state for the currently playing track (clobbers A)
; (currently playing SFX will be muted alongside track playback)
tambo_pauseTrack:
		lda tamboPauseStatus
		eor #$80
		sta tamboPauseStatus
		bpl @resume	; but only mute upon setting pause
		txa
		pha
		tya
		pha
		jsr initAPURegs ; clobbers AXY
		jsr initSFX
		jmp pullXY
@resume:
		rts

; stop all audio (clobbers A)
; (currently playing SFX will also be muted)
tambo_stopTrack:
		txa
		pha
		tya
		pha
		jsr tambo_initAPU
		jmp pullXY

initAPURegs:
		lda #$00 ; mute everything including DMC
		sta $4015 ; (avoids register activation bugs during the init loop)
		ldy #$13
@loop:
		lda tambo_registerInitTable,y
 		sta $4000,y
 		sta apuMirrors,y ; init register mirrors, too
 		dey
 		bpl @loop

 		ldx #%11001111
 		stx $4015 ; enable APU channels except DMC (low 4 bits)
 		stx $4017 ; 5-step mode, disable IRQs (high 2 bits)
 		rts

tambo_initAPU:
 		jsr initAPURegs
 		stx tamboPauseStatus ; X has bit 7 set
 		
 		; fall back to NTSC tempo/pitch for bad region settings (e.g. overclocked emulators)
 		ldy soundRegion
 		cpy #REGION::BAD
 		bcc @regionValid
		ldy #REGION::NTSC
		sty soundRegion
@regionValid:
		lda #$00
		sta currentTrack
		sta currentSFX
		jsr initSFX
		
tambo_initRAM:
		lda #$00
		ldx #$04
@loop:
		sta channelKeyOn,x
		sta channelNoteCounters,x
		sta channelLoopCounter1,x
		sta channelLoopCounter2,x
		sta channelTransposition,x
		dex
		bpl @loop
		sta tickCounter
		sta speedCounter
		sta speedSetting
 		rts

initSFX:
		ldx #$01
		jsr initSFXSlot
		dex ; fall through to init slot 0

initSFXSlot:
		lda #$ff
		sta sfxChannelIndexes,x ; negative value = free slot
		lda #$00
		sta sfxPointers_Lo,x
		sta sfxPointers_Hi,x
		sta sfxTransposition,x
		sta sfxNoteCounters,x
		sta sfxTickCounters,x
		sta sfxSpeedSettings,x
		sta sfxSpeedCounters,x
		rts

; SFX will not load if:
; - currentSFX >= [tambo_maxSFX]
; - channel index in SFX data > 4
; - speed setting in SFX data = 0
; - both SFX slots are occupied with other channels
tambo_playSFX:
		txa
		pha
		tya
		pha
		ldy currentSFX
		cpy tambo_maxSFX
		bcc @checkChannelIndex
@invalid:
		jmp pullXY
		
@checkChannelIndex:
		lda sfxHeaders_Lo,y
		sta pointer16
		lda sfxHeaders_Hi,y
		sta pointer16+1
		ldy #$00
		lda (pointer16),y ; channel index
		cmp #$05
		bcs @invalid
		
		; load to the first SFX slot already using that channel,
		; otherwise pick the first free slot
		; if both slots are in use, give up for now
		; (since that would risk leaving a channel running)
		ldx #$00 ; start at slot 0
		cmp sfxChannelIndexes
		beq @checkSpeed ; slot 0 matches
		inx
		cmp sfxChannelIndexes+1
		beq @checkSpeed ; slot 1 matches
		dex
		bit sfxChannelIndexes
		bmi @checkSpeed ; slot 0 free
		inx
		bit sfxChannelIndexes+1
		bpl @invalid ; slot 1 not free either? give up

@checkSpeed:
		pha
		iny
		lda (pointer16),y ; speed setting
		bne @loadSFX
		pla
		jmp pullXY ; reject if speed = 0

@loadSFX:
		; set up the SFX slot
		sta sfxSpeedSettings,x
		pla
		sta sfxChannelIndexes,x
		lda #$00
		sta sfxTransposition,x
		sta sfxNoteCounters,x
		sta sfxKeyOn,x
		sta sfxTickCounters,x
		sta sfxSpeedCounters,x
		tya ; add Y+1 to pointer to point to start of SFX notes
		sec
		adc pointer16
		sta sfxPointers_Lo,x
		lda pointer16+1
		adc #$00
		sta sfxPointers_Hi,x
		jmp pullXY

; track will not load if:
; - currentTrack >= [tambo_maxTracks]
; - speed setting in track data = 0
tambo_playTrack:
		txa
		pha
		tya
		pha
		ldy currentTrack
		cpy tambo_maxTracks ; reject invalid track numbers
		bcs pullXY

		; if valid, load the initial pattern pointers from the header
		jsr tambo_initRAM
		lda trackHeaders_Lo,y
		sta pointer16
		lda trackHeaders_Hi,y
		sta pointer16+1
		lda #$00
		tax
		tay
		lda (pointer16),y ; speed setting
		beq pullXY ; reject if speed = 0
		sta speedSetting
		
@headerLoadLoop:
		iny
		lda (pointer16),y
		sta channelPatternPointers_Lo,x
		iny
		lda (pointer16),y
		sta channelPatternPointers_Hi,x
		; set the initial note pointer to a location containing 0
		lda #<ALWAYS_ZERO
		sta channelNotePointers_Lo,x
		lda #>ALWAYS_ZERO
		sta channelNotePointers_Hi,x
		inx
		cpx #$05
		bne @headerLoadLoop

		lda #$00
		sta tamboPauseStatus
pullXY:
		pla
		tay
		pla
		tax
		rts

tambo_soundUpdate:
		bit tamboPauseStatus
		bmi parseSFX
		lda speedSetting ; 0 usually means we haven't called playTrack yet
		beq parseSFX
@runSound:
		ldx #$04
		stx channelIndex
@channelParseLoop:
		jsr tambo_readNote
		ldx channelIndex
		lda channelKeyOn,x
		beq @noHandler
		cpx #$3
		bcs @noHandler
		
		jsr noteLookup
		
@noHandler:
		dec channelIndex
		bpl @channelParseLoop
		
parseSFX:
		lda #$01
		sta sfxSlot
		jsr tambo_readSFX
		dec sfxSlot
		jsr tambo_readSFX
		
tambo_updateAPU:
		ldx #$ff ; manually tick APU frame counter to skip the 5th step
		stx $4017
updatePulse1:
		lda channelKeyOn
		beq updatePulse2
		dec channelKeyOn
		lda channelMuteStates
		bne updatePulse2
		lda pulse1Mirrors
		sta $4000
		lda pulse1Mirrors+1
		sta $4001
		stx $4017
		lda pulse1Mirrors+2
		sta $4002
		lda pulse1Mirrors+3
		sta $4003

updatePulse2:
		lda channelKeyOn+1
		beq updateTriangle
		dec channelKeyOn+1
		lda channelMuteStates+1
		bne updateTriangle
		lda pulse2Mirrors
		sta $4004
		lda pulse2Mirrors+1
		sta $4005
		stx $4017
		lda pulse2Mirrors+2
		sta $4006
		lda pulse2Mirrors+3
		sta $4007

updateTriangle:
		lda triangleMirrors+1 ; nonzero = force on (i.e. linear counter trill)
		bne @forceOn
		lda channelKeyOn+2
		beq updateNoise
@forceOn:
		inx ; X = 0 (done with ticking the frame counter)
		stx channelKeyOn+2
		lda channelMuteStates+2
		bne updateNoise
		lda triangleMirrors
		sta $4008
		lda triangleMirrors+2
		sta $400a
		lda triangleMirrors+3
		sta $400b

updateNoise:
		lda channelKeyOn+3
		beq updateDMC
		dec channelKeyOn+3
		lda channelMuteStates+3
		bne updateDMC
		lda noiseMirrors
		sta $400c
		lda noiseMirrors+2
		sta $400e
		lda noiseMirrors+3
		sta $400f

updateDMC:
		lda channelKeyOn+4
		beq updateSFX
		dec channelKeyOn+4
		lda channelMuteStates+4
		bne updateSFX
		lda #$0f ; preemptively mute DMC
		sta $4015
		lda dmcMirrors
		bmi tambo_tickCounters ; bit 7 set = keep DMC muted
		sta $4010
		lda dmcMirrors+1
		bmi @skipDirectLoad ; bit 7 set = skip direct load
		sta $4011
@skipDirectLoad:
		lda dmcMirrors+2
		sta $4012
		lda dmcMirrors+3
		sta $4013
		; (re)trigger DMC DMA
		lda #$1f
		sta $4015

updateSFX:
		lda #$01
		sta sfxSlot
		jsr tambo_writeSFX
		dec sfxSlot
		jsr tambo_writeSFX

tambo_tickCounters:
		ldy soundRegion
		lda tambo_tickRates,y
		sta tamboTemp
		
		bit tamboPauseStatus
		bmi tickSFXCounters
		lda speedSetting ; 0 usually means we haven't called playTrack yet
		beq tickSFXCounters
		
		ldy #$00
		lda tickCounter
		clc
		adc #TEMPO
		bcc @checkTempoMod
@tempoModLoop:
		sbc tamboTemp
		iny
@checkTempoMod:
		cmp tamboTemp
		bcs @tempoModLoop
		sta tickCounter
		tya
		adc speedCounter ; carry always clear
		ldy #$00
		bcc @checkSpeedMod
@speedModLoop:
		sbc speedSetting
		iny
@checkSpeedMod:
		cmp speedSetting
		bcs @speedModLoop
		sta speedCounter
		cpy #$00
		beq tickSFXCounters
		ldx #$04
@channelLoop:
		lda channelNoteCounters,x
		beq @alreadyZero
		dec channelNoteCounters,x
@alreadyZero:
		dex
		bpl @channelLoop
		
tickSFXCounters:
		ldx #$01
		jsr tickSFXCounter
		dex ; fall through to tick slot 0

; SFX durations are treated as speed 1 rows
tickSFXCounter:
		lda sfxChannelIndexes,x
		bmi @skip ; skip if free slot
		lda sfxSpeedSettings,x
		beq @skip ; in case the speed was somehow set to 0
		
		ldy #$00
		lda sfxTickCounters,x
		clc
		adc #TEMPO
		bcc @checkTempoMod
@tempoModLoop:
		sbc tamboTemp ; still contains the region tick rate
		iny
@checkTempoMod:
		cmp tamboTemp
		bcs @tempoModLoop
		sta sfxTickCounters,x
		tya
		adc sfxSpeedCounters,x ; carry always clear
		ldy #$00
		bcc @checkSpeedMod
@speedModLoop:
		sbc sfxSpeedSettings,x
		iny
@checkSpeedMod:
		cmp sfxSpeedSettings,x
		bcs @speedModLoop
		sta sfxSpeedCounters,x
		cpy #$00
		beq @skip
		lda sfxNoteCounters,x
		beq @skip
		dec sfxNoteCounters,x
@skip:
		rts

refetchPattern:
		jsr updatePatternPointer ; then fall through to pattern refetch
		
tambo_readPattern:
		ldx channelIndex
		lda channelPatternPointers_Lo,x
		sta pointer16
		lda channelPatternPointers_Hi,x
		sta pointer16+1
		ldy #$00
		lda (pointer16),y
		sta channelNotePointers_Lo,x
		iny
		lda (pointer16),y
		sta channelNotePointers_Hi,x
		bpl patternCommand ; pattern addresses < $8000 are pattern commands
		
updatePatternPointer:
		tya ; add Y+1 to pointer so it points to the next pattern
		sec
		adc pointer16
		sta channelPatternPointers_Lo,x
		bcc endOfSong
		inc channelPatternPointers_Hi,x
endOfSong:
		rts

; address < $8000 means this is a pattern command
patternCommand:
		lda channelNotePointers_Lo,x ; read command ID
		beq endOfSong ; $xx00 = end song (for that channel)
		
		cmp #<CMD::JUMP ; $xxff = pattern jump
		beq @patternJump
		
		cmp #<CMD::LOOP_JUMP1
		beq @checkLoopCounter1
		
		cmp #<CMD::SET_LOOP1
		beq @setLoopCounter1
		
		cmp #<CMD::TRANSPOSE
		beq @transpose
		
		cmp #<CMD::LOOP_JUMP2
		beq @checkLoopCounter2
		
		cmp #<CMD::SET_LOOP2
		bne endOfSong ; treat all remaining commands as "end song" for now

@setLoopCounter2:
		lda channelNotePointers_Hi,x ; high byte = loop counter value 2
		sta channelLoopCounter2,x
		jmp refetchPattern

@setLoopCounter1:
		lda channelNotePointers_Hi,x ; high byte = loop counter value 1
		sta channelLoopCounter1,x
		jmp refetchPattern

@transpose:
		lda channelNotePointers_Hi,x ; high byte = transposition offset
		asl a ; sign extend from 7-bit to 8-bit
		cmp #$80
		ror a
		adc channelTransposition,x ; carry always clear
		sta channelTransposition,x
		jmp refetchPattern
		
@checkLoopCounter1:
		lda channelLoopCounter1,x
		beq @nextPattern
		dec channelLoopCounter1,x
		jmp @patternJump

@checkLoopCounter2:
		lda channelLoopCounter2,x
		bne @decLoopCounter2
@nextPattern:
		iny ; if loop counter = 0, progress to next pattern
		iny
		jmp refetchPattern
		
@decLoopCounter2:
		dec channelLoopCounter2,x ; then fall through to handling the jump

		; JUMP: fetch next 2 bytes & set as new pattern pointer
@patternJump:
		iny
		lda (pointer16),y
		sta channelPatternPointers_Lo,x
		iny
		lda (pointer16),y
		sta channelPatternPointers_Hi,x
		; then read the new pattern
		jmp tambo_readPattern

tambo_readNote:
		ldx channelIndex
		lda channelNoteCounters,x ; wait until counter becomes 0
		beq @checkNotePointer
@noNewNote:
		rts

@refetchPatternThenNote:
		jsr tambo_readPattern

@checkNotePointer:
		lda channelNotePointers_Hi,x ; (avoid reading a stale pattern command)
		bpl @noNewNote

@fetchNote:
		lda channelNotePointers_Lo,x
		sta pointer16
		lda channelNotePointers_Hi,x
		sta pointer16+1
		ldy #$00
		lda (pointer16),y ; note duration
		beq @refetchPatternThenNote ; if duration is 0, read the next pattern

@newNote:
		sta channelNoteCounters,x

		; copy the next 4 bytes into the APU reg mirrors
		txa
		asl a ; channelIndex x 4
		asl a
		tax
@rowReadLoop:
		iny
		lda (pointer16),y
		sta apuMirrors,x
		inx
		cpy #4
		bcc @rowReadLoop
		
		; add Y+1 to pointer so it points to the next note
		ldx channelIndex
		tya
		adc pointer16 ; carry already set
		sta channelNotePointers_Lo,x
		bcc @noCarry
		inc channelNotePointers_Hi,x
@noCarry:
		inc channelKeyOn,x ; signal key on
noSFX:
		rts

tambo_readSFX:
		ldx sfxSlot
		lda sfxChannelIndexes,x
		bmi noSFX ; skip if slot is free
		
		sta channelIndex ; music has finished using this
		lda sfxNoteCounters,x ; wait until counter becomes 0
		bne noSFX
		
		lda sfxPointers_Hi,x
		bpl noSFX ; (avoid using stale data)
		
		sta pointer16+1
		lda sfxPointers_Lo,x
		sta pointer16
		ldy #$00
		lda (pointer16),y ; duration
		bne @loadRegs

		ldx sfxSlot
		lda #$ff
		sta sfxChannelIndexes,x ; mark slot as clear
		tya
		ldx channelIndex
		sta channelMuteStates,x ; clear channel mute state
		rts

@loadRegs:
		sta sfxNoteCounters,x
		txa
		asl a
		asl a
		sta tamboTemp
		tax
@rowReadLoop:
		iny
		lda (pointer16),y
		sta sfxMirrors,x
		inx
		cpy #$04
		bcc @rowReadLoop
		
		; add Y+1 to pointer so it points to the next note
		ldx sfxSlot
		tya
		adc pointer16 ; carry already set
		sta sfxPointers_Lo,x
		bcc @noCarry
		inc sfxPointers_Hi,x
@noCarry:
		inc sfxKeyOn,x ; key-on
		
		ldy channelIndex
		lda #$01
		sta channelMuteStates,y ; mute music channel
		
		cpy #$03
		bcs noSFX
		
		; set up channelIndex so we can reuse the note lookup routine
		txa
		adc #5 ; carry already clear
		sta channelIndex ; treat SFX slots 0-1 as channel indexes 5-6
		tax
		
; note lookup for pulse/triangle
noteLookup:
		txa
		sec
		rol a ; channelIndex * 4 + 2
		asl a
		tax
		lda apuMirrors,x
		cmp #REST ; check for rest note
		beq @restNote
		cmp #CUT ; check for note cut
		bcc @validNote
		
; only pulse/triangle get note cut support
; (noise/DMC need explicit muting within song data)
@noteCut:
		dex ; X = channelIndex * 4
		dex
		cpx #(5*4) ; are we handling an SFX slot?
		bcs muteSFX
@notSFX:
		ldy #$03
@initChannelLoop:
		lda tambo_registerInitTable,x
		sta apuMirrors,x
		inx
		dey
		bpl @initChannelLoop
		bmi @skipHighPeriod ; [unconditional branch]
		
@restNote:
		ldx channelIndex
		dec channelKeyOn,x ; forcefully key-off
		beq @skipHighPeriod ; [unconditional branch]

@validNote:
		ldy soundRegion ; transpose based on the region
		adc tambo_noteAdjustments,y ; carry already clear
		stx tamboTemp ; temporarily save offset into apuMirrors
		ldx channelIndex
		clc
		adc channelTransposition,x ; apply transposition
		tay
		ldx tamboTemp
		lda periodTableLo,y
		sta apuMirrors,x
		inx
		cpy #36 ; high period byte is always 0 past this note
		bcs @skipHighPeriod ; (assume length counter value contains that 0)
		lda periodTableHi,y
		ora apuMirrors,x ; combine with length counter
		sta apuMirrors,x
@skipHighPeriod:
		rts

muteSFX:
		lda sfxSlot
		asl a
		asl a
		tax ; = sfxSlot * 4
		ldy tamboTemp ; still contains SFX channel index * 4
		lda #$03
		sta tamboTemp ; oops, we ran out of counters...
@initChannelLoop:
		lda tambo_registerInitTable,y
		sta sfxMirrors,x
		inx
		iny
		dec tamboTemp
		bpl @initChannelLoop
		rts

tambo_writeSFX:
		ldx sfxSlot
		lda sfxChannelIndexes,x
		sta channelIndex ; music has finished using this
		bmi @skip ; skip if slot is free
		
		ldy #$ff
		txa
		asl a
		asl a
		sta tamboTemp ; = sfxSlot * 4
		
		ldx channelIndex ; use as jump table index
		lda @channelHandlers_Hi,x
		pha
		lda @channelHandlers_Lo,x
		pha
@skip:
		rts

@channelHandlers_Lo:
	.byte <(pulse1Handler-1)
	.byte <(pulse2Handler-1)
	.byte <(triangleHandler-1)
	.byte <(noiseHandler-1)
	.byte <(dmcHandler-1)
@channelHandlers_Hi:
	.byte >(pulse1Handler-1)
	.byte >(pulse2Handler-1)
	.byte >(triangleHandler-1)
	.byte >(noiseHandler-1)
	.byte >(dmcHandler-1)

pulse1Handler:
		ldx sfxSlot
		lda sfxKeyOn,x
		beq @skip
		dec sfxKeyOn,x
		ldx tamboTemp
		lda sfxMirrors,x
		sta $4000
		lda sfxMirrors+1,x
		sta $4001
		sty $4017
		lda sfxMirrors+2,x
		sta $4002
		lda sfxMirrors+3,x
		sta $4003
@skip:
		rts

pulse2Handler:
		ldx sfxSlot
		lda sfxKeyOn,x
		beq @skip
		dec sfxKeyOn,x
		ldx tamboTemp
		lda sfxMirrors,x
		sta $4004
		lda sfxMirrors+1,x
		sta $4005
		sty $4017
		lda sfxMirrors+2,x
		sta $4006
		lda sfxMirrors+3,x
		sta $4007
@skip:
		rts

triangleHandler:
		ldx tamboTemp
		lda sfxMirrors+1,x ; nonzero = force on (i.e. linear counter trill)
		bne @forceOn
		ldx sfxSlot
		lda sfxKeyOn,x
		beq @skip
@forceOn:
		ldx sfxSlot
		iny ; Y = 0
		sty sfxKeyOn,x
		ldx tamboTemp
		lda sfxMirrors,x
		sta $4008
		lda sfxMirrors+2,x
		sta $400a
		lda sfxMirrors+3,x
		sta $400b
@skip:
		rts

noiseHandler:
		ldx sfxSlot
		lda sfxKeyOn,x
		beq @skip
		dec sfxKeyOn,x
		ldx tamboTemp
		lda sfxMirrors,x
		sta $400c
		lda sfxMirrors+2,x
		sta $400e
		lda sfxMirrors+3,x
		sta $400f
@skip:
		rts

dmcHandler:
		ldx sfxSlot
		lda sfxKeyOn,x
		beq @skip
		dec sfxKeyOn,x
		ldx tamboTemp
		lda #$0f ; preemptively mute DMC
		sta $4015
		lda sfxMirrors,x
		bmi @skip ; bit 7 set = keep DMC muted
		sta $4010
		lda sfxMirrors+1,x
		bmi @skipDirectLoad ; bit 7 set = skip direct load
		sta $4011
@skipDirectLoad:
		lda sfxMirrors+2,x
		sta $4012
		lda sfxMirrors+3,x
		sta $4013
		; (re)trigger DMC DMA
		lda #$1f
		sta $4015
@skip:
		rts


