; Tambo Sound Driver by TakuikaNinja

; NTSC period table generated by mktables.py
; (includes a C8 note entry currently only accessible via PAL transposition)
periodTableLo:
	.byte $f1,$7f,$13,$ad,$4d,$f3,$9d,$4c,$00,$b8,$74,$34
	.byte $f8,$bf,$89,$56,$26,$f9,$ce,$a6,$80,$5c,$3a,$1a
	.byte $fb,$df,$c4,$ab,$93,$7c,$67,$52,$3f,$2d,$1c,$0c
	.byte $fd,$ef,$e1,$d5,$c9,$bd,$b3,$a9,$9f,$96,$8e,$86
	.byte $7e,$77,$70,$6a,$64,$5e,$59,$54,$4f,$4b,$46,$42
	.byte $3f,$3b,$38,$34,$31,$2f,$2c,$29,$27,$25,$23,$21
	.byte $1f,$1d,$1b,$1a,$18,$17,$15,$14,$13,$12,$11,$10
	.byte $0f,$0e,$0d
periodTableHi:
	.byte $07,$07,$07,$06,$06,$05,$05,$05,$05,$04,$04,$04
	.byte $03,$03,$03,$03,$03,$02,$02,$02,$02,$02,$02,$02
	.byte $01,$01,$01,$01,$01,$01,$01,$01,$01,$01,$01,$01
;	.byte $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
;	.byte $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
;	.byte $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
;	.byte $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
;	.byte $00,$00,$00

; indexed by soundRegion (0-2):
; NTSC = use note lookup as-is, tempo 150
; PAL = transpose up 1 semitone (dirty hack), tempo 125
; DenDy = use note lookup as-is, tempo 125
tambo_noteAdjustments:
	.byte 0, 1, 0
tambo_tickRates:
	.byte 150, 125, 125

; APU init code based on https://www.nesdev.org/wiki/APU_basics#Register_initialization
tambo_registerInitTable:
	.byte $30,$08,$00,$00
	.byte $30,$08,$00,$00
	.byte $80,$00,$00,$00
	.byte $30,$00,$00,$00
	.byte $00,$00,$00,$00

tambo_initAPU:
 		ldy #$13
@loop:  lda tambo_registerInitTable,y
 		sta $4000,y
 		sta apuMirrors,y ; init register mirrors, too
 		dey
 		bpl @loop

 		ldx #%11001111
 		stx $4015 ; enable APU channels except DMC (low 4 bits)
 		stx $4017 ; 5-step mode, disable IRQs (high 2 bits)
 		stx tamboPauseStatus ; in case updateSound runs before playTrack
 		
 		; fall back to NTSC tempo/pitch for bad region settings (e.g. overclocked emulators)
 		ldy soundRegion
 		cpy #REGION::BAD
 		bcc @regionValid
		ldy #REGION::NTSC
		sty soundRegion
@regionValid:
		lda #$00
		sta currentTrack
		
tambo_initRAM:
		lda #$00
		ldx #$04
@loop:
		sta channelKeyOn,x
		sta channelNoteCounters,x
		dex
		bpl @loop
		sta tickCounter
		sta speedCounter
		sta speedSetting
 		rts

tambo_playTrack:
		txa
		pha
		tya
		pha
		ldy currentTrack
		cpy tambo_maxTracks ; reject invalid track numbers
		bcc @valid

		jsr tambo_stopTrack
		jmp @pullXY

; if valid, load the initial pattern pointers from the header
@valid:
		jsr tambo_initRAM
		lda trackHeaders_Lo,y
		sta pointer16
		lda trackHeaders_Hi,y
		sta pointer16+1
		lda #$00
		tax
		tay
		lda (pointer16),y ; speed setting
		sta speedSetting
		iny
		
@headerLoadLoop:
		lda (pointer16),y
		sta channelPatternPointers_Lo,x
		iny
		lda (pointer16),y
		sta channelPatternPointers_Hi,x
		iny
		inx
		cpx #$05
		bne @headerLoadLoop

; then fetch the initial note pointers
		dex
		stx channelIndex
@notePointerLoadLoop:
		jsr tambo_readPattern
		dec channelIndex
		bpl @notePointerLoadLoop

		lda #$00
		sta tamboPauseStatus
@pullXY:
		pla
		tay
		pla
		tax
		rts

tambo_stopTrack:
		lda #$80
		bmi tambo_setPauseStatus

tambo_pauseTrack:
		lda #$00
tambo_setPauseStatus:
		sta tamboPauseStatus
		rts

tambo_soundUpdate:
		lda tamboPauseStatus
		bpl @runSound
		rts
@runSound:
		ldx #$04
		stx channelIndex
@channelParseLoop:
		jsr tambo_readNote
		ldx channelIndex
		lda channelKeyOn,x
		beq @noHandler
		cpx #$3
		bcs @noHandler
@noteLookup:
		txa
		sec
		rol a ; channelIndex * 4 + 2
		asl a
		tax
		lda apuMirrors,x
		cmp #REST ; check for rest note
		bcc @validNote
		
@invalidNote:
		ldx channelIndex
		dec channelKeyOn,x ; forcefully key-off
		beq @skipHighPeriod ; [unconditional branch]

@validNote:
		ldy soundRegion ; transpose based on the region
		adc tambo_noteAdjustments,y ; [carry always clear]
		cmp #NOTE_CEILING ; check the transposed result is within bounds
		bcs @invalidNote ; otherwise forcefully key-off
		
		tay
		lda periodTableLo,y
		sta apuMirrors,x
		inx
		cpy #36 ; high period byte is always 0 past this note
		bcs @skipHighPeriod ; (assume length counter value contains that 0)
		lda periodTableHi,y
		ora apuMirrors,x ; combine with length counter
		sta apuMirrors,x
@skipHighPeriod:
@noHandler:
		dec channelIndex
		bpl @channelParseLoop
		
tambo_updateAPU:
		ldx #$ff ; manually tick APU frame counter to skip the 5th step
updatePulse1:
		lda channelKeyOn
		beq updatePulse2
		dec channelKeyOn
		lda pulse1Mirrors
		sta $4000
		lda pulse1Mirrors+1
		sta $4001
		stx $4017
		lda pulse1Mirrors+2
		sta $4002
		lda pulse1Mirrors+3
		sta $4003

updatePulse2:
		lda channelKeyOn+1
		beq updateTriangle
		dec channelKeyOn+1
		lda pulse2Mirrors
		sta $4004
		lda pulse2Mirrors+1
		sta $4005
		stx $4017
		lda pulse2Mirrors+2
		sta $4006
		lda pulse2Mirrors+3
		sta $4007

updateTriangle:
		lda channelKeyOn+2
		beq updateNoise
		dec channelKeyOn+2
		lda triangleMirrors
		sta $4008
		lda triangleMirrors+2
		sta $400a
		lda triangleMirrors+3
		sta $400b

updateNoise:
		lda channelKeyOn+3
		beq updateDMC
		dec channelKeyOn+3
		lda noiseMirrors
		sta $400c
		lda noiseMirrors+2
		sta $400e
		lda noiseMirrors+3
		sta $400f

updateDMC:
		lda channelKeyOn+4
		beq tambo_tickCounters
		dec channelKeyOn+4
		lda #$0f ; preemptively mute DMC
		sta $4015
		lda dmcMirrors
		bmi tambo_tickCounters ; bit 7 set = keep DMC muted
		sta $4010
		lda dmcMirrors+1
		bmi @skipDirectLoad ; bit 7 set = skip direct load
		sta $4011
@skipDirectLoad:
		lda dmcMirrors+2
		sta $4012
		lda dmcMirrors+3
		sta $4013
		; (re)trigger DMC DMA
		lda #$1f
		sta $4015

tambo_tickCounters:
		ldy soundRegion
		lda tambo_tickRates,y
		sta tamboTemp
		ldy speedCounter
		lda tickCounter
		clc
		adc #TEMPO
		bcc @checkMod
@modLoop:
		sbc tamboTemp
		iny
@checkMod:
		cmp tamboTemp
		bcs @modLoop
@tickCounters:
		sta tickCounter
		sty speedCounter
		tya
		cmp speedSetting
		bcc @skip
		sbc speedSetting
		sta speedCounter
		ldx #$04
@channelLoop:
		lda channelNoteCounters,x
		beq @alreadyZero
		dec channelNoteCounters,x
@alreadyZero:
		dex
		bpl @channelLoop
@skip:
		rts

fetchPattern:
		ldx channelIndex
		lda channelPatternPointers_Lo,x
		sta pointer16
		lda channelPatternPointers_Hi,x
		sta pointer16+1
		ldy #$00
		lda (pointer16),y
		sta channelNotePointers_Lo,x
		iny
		lda (pointer16),y
		sta channelNotePointers_Hi,x
		iny
		cmp #$00 ; pattern addresses < $8000 are pattern commands
		rts

tambo_readPattern:
		jsr fetchPattern
		bmi @updatePatternPointer
		
		; address < $8000 means this is a pattern command
		lda channelNotePointers_Lo,x ; read command ID
		beq @endOfSong ; $xx00 = end song (for that channel)
		cmp #<CMD::JUMP ; $xxff = pattern jump
		bne @endOfSong ; treat all remaining commands as "end song" for now
		
		; JUMP: fetch next 2 bytes & set as new pattern pointer
		lda (pointer16),y
		sta channelPatternPointers_Lo,x
		iny
		lda (pointer16),y
		sta channelPatternPointers_Hi,x
		; then refetch pattern
		jmp tambo_readPattern
		
@updatePatternPointer:
		tya
		clc
		adc channelPatternPointers_Lo,x
		sta channelPatternPointers_Lo,x
		lda channelPatternPointers_Hi,x
		adc #$00
		sta channelPatternPointers_Hi,x
@endOfSong:
		rts

fetchNote:
		lda channelNotePointers_Lo,x
		sta pointer16
		lda channelNotePointers_Hi,x
		sta pointer16+1
		ldy #$00
		lda (pointer16),y ; note duration
		rts

tambo_readNote:
		ldx channelIndex
		lda channelNoteCounters,x ; wait until counter becomes 0
		bne @noNewNote

@checkNotePointer:
		lda channelNotePointers_Hi,x ; (avoid reading a stale pattern command)
		bpl @noNewNote
		
		jsr fetchNote
		bne @newNote ; and proceed if duration is nonzero
		
		jsr tambo_readPattern ; if duration is 0, read the next pattern
		jmp @checkNotePointer ; and refetch the note

@newNote:
		sta channelNoteCounters,x

		; copy the next 4 bytes into the APU reg mirrors
		iny
		txa
		asl a ; channelIndex x 4
		asl a
		tax
@rowReadLoop:
		lda (pointer16),y
		sta apuMirrors,x
		inx
		iny
		cpy #5
		bne @rowReadLoop
		
		; add Y to pointer so it points to the next note
		ldx channelIndex
		tya
		clc
		adc pointer16
		sta channelNotePointers_Lo,x
		lda pointer16+1
		adc #$00
		sta channelNotePointers_Hi,x
		inc channelKeyOn,x ; signal key on
		
@noNewNote:
		rts

