; Tambo Sound Driver by TakuikaNinja

; NTSC period table generated by mktables.py
; (includes a C8 note entry currently only accessible via PAL transposition)
periodTableLo:
	.byte $f1,$7f,$13,$ad,$4d,$f3,$9d,$4c,$00,$b8,$74,$34
	.byte $f8,$bf,$89,$56,$26,$f9,$ce,$a6,$80,$5c,$3a,$1a
	.byte $fb,$df,$c4,$ab,$93,$7c,$67,$52,$3f,$2d,$1c,$0c
	.byte $fd,$ef,$e1,$d5,$c9,$bd,$b3,$a9,$9f,$96,$8e,$86
	.byte $7e,$77,$70,$6a,$64,$5e,$59,$54,$4f,$4b,$46,$42
	.byte $3f,$3b,$38,$34,$31,$2f,$2c,$29,$27,$25,$23,$21
	.byte $1f,$1d,$1b,$1a,$18,$17,$15,$14,$13,$12,$11,$10
	.byte $0f,$0e,$0d
periodTableHi:
	.byte $07,$07,$07,$06,$06,$05,$05,$05,$05,$04,$04,$04
	.byte $03,$03,$03,$03,$03,$02,$02,$02,$02,$02,$02,$02
	.byte $01,$01,$01,$01,$01,$01,$01,$01,$01,$01,$01,$01
;	.byte $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
;	.byte $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
;	.byte $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
;	.byte $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
;	.byte $00,$00,$00

; indexed by soundRegion (0-2):
; NTSC = use note lookup as-is, tempo 150
; PAL = transpose up 1 semitone (dirty hack), tempo 125
; DenDy = use note lookup as-is, tempo 125
tambo_noteAdjustments:
	.byte 0, 1, 0
tambo_tickRates:
	.byte 150, 125, 125

; APU init code based on https://www.nesdev.org/wiki/APU_basics#Register_initialization
tambo_registerInitTable:
	.byte $30,$08,$00,$00
	.byte $30,$08,$00,$00
	.byte $80,$00,$00,$00
	.byte $30,$00,$00,$00
	.byte $00,$00,$00,$00

; toggle pause state for the currently playing track (clobbers A)
; (currently playing SFX will be muted alongside track playback)
tambo_pauseTrack:
		lda tamboPauseStatus
		eor #$80
		sta tamboPauseStatus
		bpl @resume	; but only mute upon setting pause
		txa
		pha
		tya
		pha
		jsr initAPURegs ; clobbers AXY
		jmp pullXY
@resume:
		rts

; stop all audio (clobbers A)
; (currently playing SFX will also be muted)
tambo_stopTrack:
		txa
		pha
		tya
		pha
		jmp initAPUThenPullXY

initAPURegs:
		lda #$00 ; mute everything including DMC
		sta $4015 ; (avoids register activation bugs during the init loop)
		ldy #$13
@loop:
		lda tambo_registerInitTable,y
 		sta $4000,y
 		sta apuMirrors,y ; init register mirrors, too
 		dey
 		bpl @loop

 		ldx #%11001111
 		stx $4015 ; enable APU channels except DMC (low 4 bits)
 		stx $4017 ; 5-step mode, disable IRQs (high 2 bits)
 		rts

tambo_initAPU:
 		jsr initAPURegs
 		stx tamboPauseStatus ; X has bit 7 set
 		
 		; fall back to NTSC tempo/pitch for bad region settings (e.g. overclocked emulators)
 		ldy soundRegion
 		cpy #REGION::BAD
 		bcc @regionValid
		ldy #REGION::NTSC
		sty soundRegion
@regionValid:
		lda #$00
		sta currentTrack
		
tambo_initRAM:
		lda #$00
		ldx #$04
@loop:
		sta channelKeyOn,x
		sta channelNoteCounters,x
		sta channelLoopCounter1,x
		sta channelLoopCounter2,x
		sta channelTransposition,x
		dex
		bpl @loop
		sta tickCounter
		sta speedCounter
		sta speedSetting
 		rts

tambo_playTrack:
		txa
		pha
		tya
		pha
		ldy currentTrack
		cpy tambo_maxTracks ; reject invalid track numbers
		bcc validTrack

initAPUThenPullXY:
		jsr tambo_initAPU
		jmp pullXY

; if valid, load the initial pattern pointers from the header
validTrack:
		jsr tambo_initRAM
		lda trackHeaders_Lo,y
		sta pointer16
		lda trackHeaders_Hi,y
		sta pointer16+1
		lda #$00
		tax
		tay
		lda (pointer16),y ; speed setting
		sta speedSetting
		iny
		
@headerLoadLoop:
		lda (pointer16),y
		sta channelPatternPointers_Lo,x
		iny
		lda (pointer16),y
		sta channelPatternPointers_Hi,x
		iny
		inx
		cpx #$05
		bne @headerLoadLoop

; then fetch the initial note pointers
		dex
		stx channelIndex
@notePointerLoadLoop:
		jsr tambo_readPattern
		dec channelIndex
		bpl @notePointerLoadLoop

		lda #$00
		sta tamboPauseStatus
pullXY:
		pla
		tay
		pla
		tax
		rts

tambo_soundUpdate:
		bit tamboPauseStatus
		bmi @exitSound
		lda speedSetting ; 0 usually means we haven't called playTrack yet
		bne @runSound
@exitSound:
		rts ; TODO: should probably allow SFX updates
@runSound:
		ldx #$04
		stx channelIndex
@channelParseLoop:
		jsr tambo_readNote
		ldx channelIndex
		lda channelKeyOn,x
		beq @noHandler
		cpx #$3
		bcs @noHandler
		
; note lookup for pulse/triangle
@noteLookup:
		txa
		sec
		rol a ; channelIndex * 4 + 2
		asl a
		tax
		lda apuMirrors,x
		cmp #REST ; check for rest note
		beq @restNote
		cmp #CUT ; check for note cut
		bcc @validNote
		
; only pulse/triangle get note cut support
; (noise/DMC need explicit muting within song data)
@noteCut:
		dex ; X = channelIndex * 4
		dex
		ldy #$00
@initChannelLoop:
		lda tambo_registerInitTable,x
		sta apuMirrors,x
		inx
		iny
		cpy #$04
		bcc @initChannelLoop
		bcs @noHandler ; [unconditional branch]
		
@restNote:
		ldx channelIndex
		dec channelKeyOn,x ; forcefully key-off
		beq @noHandler ; [unconditional branch]

@validNote:
		ldy soundRegion ; transpose based on the region
		adc tambo_noteAdjustments,y ; carry already clear
		stx tamboTemp ; temporarily save offset into apuMirrors
		ldx channelIndex
		clc
		adc channelTransposition,x ; apply transposition
		tay
		ldx tamboTemp
		lda periodTableLo,y
		sta apuMirrors,x
		inx
		cpy #36 ; high period byte is always 0 past this note
		bcs @skipHighPeriod ; (assume length counter value contains that 0)
		lda periodTableHi,y
		ora apuMirrors,x ; combine with length counter
		sta apuMirrors,x
@skipHighPeriod:
@noHandler:
		dec channelIndex
		bpl @channelParseLoop
		
tambo_updateAPU:
		ldx #$ff ; manually tick APU frame counter to skip the 5th step
		stx $4017
updatePulse1:
		lda channelKeyOn
		beq updatePulse2
		dec channelKeyOn
		lda pulse1Mirrors
		sta $4000
		lda pulse1Mirrors+1
		sta $4001
		stx $4017
		lda pulse1Mirrors+2
		sta $4002
		lda pulse1Mirrors+3
		sta $4003

updatePulse2:
		lda channelKeyOn+1
		beq updateTriangle
		dec channelKeyOn+1
		lda pulse2Mirrors
		sta $4004
		lda pulse2Mirrors+1
		sta $4005
		stx $4017
		lda pulse2Mirrors+2
		sta $4006
		lda pulse2Mirrors+3
		sta $4007

updateTriangle:
		lda triangleMirrors+1 ; nonzero = force on (i.e. linear counter trill)
		bne @forceOn
		lda channelKeyOn+2
		beq updateNoise
@forceOn:
		lda #$00
		sta channelKeyOn+2
		lda triangleMirrors
		sta $4008
		lda triangleMirrors+2
		sta $400a
		lda triangleMirrors+3
		sta $400b

updateNoise:
		lda channelKeyOn+3
		beq updateDMC
		dec channelKeyOn+3
		lda noiseMirrors
		sta $400c
		lda noiseMirrors+2
		sta $400e
		lda noiseMirrors+3
		sta $400f

updateDMC:
		lda channelKeyOn+4
		beq tambo_tickCounters
		dec channelKeyOn+4
		lda #$0f ; preemptively mute DMC
		sta $4015
		lda dmcMirrors
		bmi tambo_tickCounters ; bit 7 set = keep DMC muted
		sta $4010
		lda dmcMirrors+1
		bmi @skipDirectLoad ; bit 7 set = skip direct load
		sta $4011
@skipDirectLoad:
		lda dmcMirrors+2
		sta $4012
		lda dmcMirrors+3
		sta $4013
		; (re)trigger DMC DMA
		lda #$1f
		sta $4015

tambo_tickCounters:
		ldy soundRegion
		lda tambo_tickRates,y
		sta tamboTemp
		ldy #$00
		lda tickCounter
		clc
		adc #TEMPO
		bcc @checkTempoMod
@tempoModLoop:
		sbc tamboTemp
		iny
@checkTempoMod:
		cmp tamboTemp
		bcs @tempoModLoop
		sta tickCounter
		tya
		clc
		adc speedCounter
		ldy #$00
		bcc @checkSpeedMod
@speedModLoop:
		sbc speedSetting
		iny
@checkSpeedMod:
		cmp speedSetting
		bcs @speedModLoop
		sta speedCounter
		cpy #$00
		beq @skip
		ldx #$04
@channelLoop:
		lda channelNoteCounters,x
		beq @alreadyZero
		dec channelNoteCounters,x
@alreadyZero:
		dex
		bpl @channelLoop
@skip:
		rts

fetchPattern:
		ldx channelIndex
		lda channelPatternPointers_Lo,x
		sta pointer16
		lda channelPatternPointers_Hi,x
		sta pointer16+1
		ldy #$00
		lda (pointer16),y
		sta channelNotePointers_Lo,x
		iny
		lda (pointer16),y
		sta channelNotePointers_Hi,x
		iny
		cmp #$00 ; pattern addresses < $8000 are pattern commands
		rts

refetchPattern:
		jsr updatePatternPointer ; then fall through to pattern refetch
		
tambo_readPattern:
		jsr fetchPattern
		bmi updatePatternPointer
		
		; address < $8000 means this is a pattern command
		lda channelNotePointers_Lo,x ; read command ID
		beq endOfSong ; $xx00 = end song (for that channel)
		
		cmp #<CMD::JUMP ; $xxff = pattern jump
		beq @patternJump
		
		cmp #<CMD::LOOP_JUMP1
		beq @checkLoopCounter1
		
		cmp #<CMD::SET_LOOP1
		beq @setLoopCounter1
		
		cmp #<CMD::TRANSPOSE
		beq @transpose
		
		cmp #<CMD::LOOP_JUMP2
		beq @checkLoopCounter2
		
		cmp #<CMD::SET_LOOP2
		bne endOfSong ; treat all remaining commands as "end song" for now

@setLoopCounter2:
		lda channelNotePointers_Hi,x ; high byte = loop counter value 2
		sta channelLoopCounter2,x
		jmp refetchPattern

@setLoopCounter1:
		lda channelNotePointers_Hi,x ; high byte = loop counter value 1
		sta channelLoopCounter1,x
		jmp refetchPattern

@transpose:
		lda channelNotePointers_Hi,x ; high byte = transposition offset
		asl a ; sign extend from 7-bit to 8-bit
		cmp #$80
		ror a
		adc channelTransposition,x ; carry always clear
		sta channelTransposition,x
		jmp refetchPattern
		
@checkLoopCounter1:
		lda channelLoopCounter1,x
		beq @nextPattern
		dec channelLoopCounter1,x
		jmp @patternJump

@checkLoopCounter2:
		lda channelLoopCounter2,x
		bne @decLoopCounter2
@nextPattern:
		iny ; if loop counter = 0, progress to next pattern
		iny
		jmp refetchPattern
		
@decLoopCounter2:
		dec channelLoopCounter2,x ; then fall through to handling the jump

		; JUMP: fetch next 2 bytes & set as new pattern pointer
@patternJump:
		lda (pointer16),y
		sta channelPatternPointers_Lo,x
		iny
		lda (pointer16),y
		sta channelPatternPointers_Hi,x
		; then refetch pattern
		jmp tambo_readPattern
		
updatePatternPointer:
		tya
		clc
		adc channelPatternPointers_Lo,x
		sta channelPatternPointers_Lo,x
		lda channelPatternPointers_Hi,x
		adc #$00
		sta channelPatternPointers_Hi,x
endOfSong:
		rts

fetchNote:
		lda channelNotePointers_Lo,x
		sta pointer16
		lda channelNotePointers_Hi,x
		sta pointer16+1
		ldy #$00
		lda (pointer16),y ; note duration
		rts

tambo_readNote:
		ldx channelIndex
		lda channelNoteCounters,x ; wait until counter becomes 0
		bne @noNewNote

@checkNotePointer:
		lda channelNotePointers_Hi,x ; (avoid reading a stale pattern command)
		bpl @noNewNote
		
		jsr fetchNote
		bne @newNote ; and proceed if duration is nonzero
		
		jsr tambo_readPattern ; if duration is 0, read the next pattern
		jmp @checkNotePointer ; and refetch the note

@newNote:
		sta channelNoteCounters,x

		; copy the next 4 bytes into the APU reg mirrors
		iny
		txa
		asl a ; channelIndex x 4
		asl a
		tax
@rowReadLoop:
		lda (pointer16),y
		sta apuMirrors,x
		inx
		iny
		cpy #5
		bne @rowReadLoop
		
		; add Y to pointer so it points to the next note
		ldx channelIndex
		tya
		clc
		adc pointer16
		sta channelNotePointers_Lo,x
		lda pointer16+1
		adc #$00
		sta channelNotePointers_Hi,x
		inc channelKeyOn,x ; signal key on
		
@noNewNote:
		rts

